/** @type {HTMLCanvasElement} **/
let canvas = document.getElementById("pokeball");
canvas.width = canvas.getBoundingClientRect().width;
canvas.height = canvas.getBoundingClientRect().height;
let ctx = canvas.getContext("2d");
ctx.translate(25, 25);
ctx.strokeStyle = "black";
ctx.fillStyle = "red";
ctx.lineWidth = 10;
ctx.beginPath();
ctx.arc(100, 100, 100, 0, - Math.PI, true);
ctx.fill();
ctx.fillStyle = "white";
ctx.beginPath();
ctx.arc(100, 100, 100, 0, Math.PI, false);
ctx.fill();
ctx.beginPath();
ctx.arc(100, 100, 35, 0, 2 * Math.PI, false);
ctx.fill();
ctx.strokeStyle = "black";
ctx.beginPath();
ctx.arc(100, 100, 100, 0, 2 * Math.PI, false);
ctx.stroke();
ctx.beginPath();
ctx.arc(100, 100, 35, 0, 2 * Math.PI, false);
ctx.stroke();
